project:
  type: website

website:
  title: "The Far Right"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: week-01.qmd
        text: Weekly Topics
      - href: assessments/index.qmd
        text: Assessments

  sidebar:
    - title: "Weekly Topics"
      style: docked
      background: light
      contents:
        - week-01.qmd
        - week-02.qmd
        - week-03.qmd
        - week-04.qmd
        - week-05.qmd
        - week-06.qmd
        - week-07.qmd
        - week-08.qmd
        - week-09.qmd
        - week-10.qmd

format:
  html:
    theme: lux
    toc: true
    css: styles.css
    mainfont: "Inter, sans-serif"
    link-external-newwindow: true	
